### ISSUE TITLE
Can't set headers after they are sent

### ISSUE THREAD

**Issue by robocop-bob** [nodesource/understanding-npm#10]
sudo npm install - OK
npm start - OK

Server is starting - OK.
Firefox opening connection - OK .
Server ends with attached errors -NOTOK.
Firefox still waiting , 0% progress:)

My env:
Darwin 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
node v0.12.4

Any advice?

```
npm start

> understanding-npm@1.0.0 prestart /Users/user/Documents/GITHUB/understanding-npm
> npm run relink


> understanding-npm@1.0.0 relink /Users/user/Documents/GITHUB/understanding-npm
> linklocal

nsight-header
unpm-downloaders
unpm-fetch-data
unpm-frontend
unpm-labels
unpm-dat
unpm-preloader
unpm-registry
unpm-screen-coords
unpm-server
unpm-storyboard
unpm-camera
unpm-system
unpm-background
gooey
unpm-packages

Linked 16 dependencies

> understanding-npm@1.0.0 start /Users/user/Documents/GITHUB/understanding-npm
> npm ex @unpm/server npm start


> @unpm/server@1.0.0 start /Users/user/Documents/GITHUB/understanding-npm/unpm-server
> babel-node .

Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
http://localhost:9966
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
_http_outgoing.js:335
    throw new Error('Can\'t set headers after they are sent.');
          ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
    at bail (/Users/user/Documents/GITHUB/understanding-npm/unpm-server/index.js:163:7)
    at /Users/user/Documents/GITHUB/understanding-npm/unpm-server/index.js:128:21
    at next (/Users/user/Documents/GITHUB/understanding-npm/node_modules/course/index.js:68:23)
    at Readable.<anonymous> (/Users/user/Documents/GITHUB/understanding-npm/unpm-server/index.js:119:21)
    at Readable.emit (events.js:107:17)
    at Labeled.<anonymous> (/Users/user/Documents/GITHUB/understanding-npm/node_modules/browserify/node_modules/read-only-stream/index.js:27:44)
    at Labeled.emit (events.js:107:17)
    at Labeled.<anonymous> (/Users/user/Documents/GITHUB/understanding-npm/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/index.js:132:18)
    at Labeled.emit (events.js:129:20)

npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.4
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! @unpm/server@1.0.0 start: `babel-node .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @unpm/server@1.0.0 start script 'babel-node .'.
npm ERR! This is most likely a problem with the @unpm/server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node .
npm ERR! You can get their info via:
npm ERR!     npm owner ls @unpm/server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/Documents/GITHUB/understanding-npm/unpm-server/npm-debug.log
npm ERR! weird error 1

npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.4
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! understanding-npm@1.0.0 start: `npm ex @unpm/server npm start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the understanding-npm@1.0.0 start script 'npm ex @unpm/server npm start'.
npm ERR! This is most likely a problem with the understanding-npm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm ex @unpm/server npm start
npm ERR! You can get their info via:
npm ERR!     npm owner ls understanding-npm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/Documents/GITHUB/understanding-npm/npm-debug.loguser
```

**Comment by rvagg** [comment]
Try using node 0.10.x and the latest npm (`npm install npm@latest -g`), this project has been developed and deployed on 0.10.

**Comment by ghost** [comment]
Hi,
thx.

Solution was:

```
sudo npm install bulk
```

change from: 

```
linklocal && linklocal --list | sudo bulk -c 'npm install --cache-min Infinity --production' 
```

to:

```
linklocal && linklocal --list | sudo bulk -c 'npm install --cache-min Infinity --production' 
```

This issue can be closed.
Thx

**Comment by hughsk** [comment]
@robbig2871 the issue was caused by using `sudo` for `npm` install; it doesn't run the `postinstall` script properly if that's the case :)
