### ISSUE TITLE
Data is Stale

### ISSUE THREAD

**Issue by joemccann** [nodesource/understanding-npm#13]
It appears the data is old as it shows 157,000 packages.  Let's update it and redeploy!

**Comment by NodeSara** [comment]
This is a known issue and in the queue for being fixed.

**Comment by julianduque** [comment]
@hughsk I'm trying to update the data running `npm run harvest` but I always get stuck with the following error:

```
> @unpm/dat@1.0.0 rebuild /Users/julianduque/MEGA/data/Development/NodeSource/understanding-npm/unpm-dat
> node .

70.499% gitProvider
all done!

/Users/julianduque/MEGA/data/Development/NodeSource/understanding-npm/unpm-dat/stats.js:107
  stats['ignored-name'] = topIgnored[0].name
                                       ^
TypeError: Cannot read property 'name' of undefined
    at getDownloadStarContrast (/Users/julianduque/MEGA/data/Development/NodeSource/understanding-npm/unpm-dat/stats.js:107:40)
    at Object.<anonymous> (/Users/julianduque/MEGA/data/Development/NodeSource/understanding-npm/unpm-dat/stats.js:15:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

any idea?

**Comment by julianduque** [comment]
Updated in https://github.com/nodesource/understanding-npm/commit/2465b6c8304d29aa6a9824a68d16681aebe90d16

Will add a cron job to update data on a weekly basis.
